---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-data-calic-cloud-v1alpha1-rediscluster
  failurePolicy: Fail
  name: vrediscluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - data.calic.cloud
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redisclusters
  sideEffects: None
