# This rule is not used by the project redis-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to data.calic.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: rediscluster-viewer-role
rules:
- apiGroups:
  - data.calic.cloud
  resources:
  - redisclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.calic.cloud
  resources:
  - redisclusters/status
  verbs:
  - get
