# This rule is not used by the project redis-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over data.calic.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: rediscluster-admin-role
rules:
- apiGroups:
  - data.calic.cloud
  resources:
  - redisclusters
  verbs:
  - '*'
- apiGroups:
  - data.calic.cloud
  resources:
  - redisclusters/status
  verbs:
  - get
